@startuml11_OrderHistory.png 
package boundary {
  class "注文履歴画面" as OrderHistoryUI<<boundary>>  {
  } 
}
package control { 
  class OrderHistoryManager<<control>> {
    +showOrderDetail(商品番号: String) 
  } 
}


package "entity" {
  class "注文" as Order<<entity>> {
    -注文番号: String
    -注文日: Int
    -注文合計金額: String
    -配送希望日: Int
    -受注状態: Int
  }
} 
  
OrderHistoryUI .right.> OrderHistoryManager: <<uses>> 
OrderHistoryUI"1" o-right-"1..1" Order
OrderHistoryManager"1" o-right-"1..1" Order
@enduml


